export const SCHEMA_STATEMENTS = [
	"PRAGMA foreign_keys = ON;",
	`CREATE TABLE IF NOT EXISTS research_jobs (
		job_id TEXT PRIMARY KEY,
		user_id TEXT NOT NULL,
		instructions TEXT NOT NULL,
		status TEXT NOT NULL DEFAULT 'pending',
		progress INTEGER,
		results TEXT,
		async_server_job_id TEXT,
		created_at TEXT NOT NULL,
		updated_at TEXT NOT NULL,
		completed_at TEXT,
		title TEXT,
		summary TEXT,
		citation_count INTEGER,
		processed_markdown TEXT,
		original_query TEXT,
		sections TEXT NOT NULL DEFAULT '[]',
		research_type TEXT NOT NULL DEFAULT 'exa',
		response_id TEXT,
		webhook_data TEXT,
		parent_id TEXT,
		job_type TEXT NOT NULL DEFAULT 'root',
		subtopic TEXT,
		order_index INTEGER,
		estimated_tokens INTEGER,
		actual_tokens INTEGER,
		started_at TEXT,
		tagged_documents TEXT,
		enhancement_options TEXT,
		running_context TEXT,
		enhanced_sections TEXT,
		section_metadata TEXT,
		enhancement_status TEXT DEFAULT 'pending',
		current_section_index INTEGER DEFAULT 0,
		total_sections INTEGER DEFAULT 0,
		enhanced_content TEXT,
		exa_research_id TEXT,
		report_note_path TEXT
	);`,
	"CREATE INDEX IF NOT EXISTS idx_research_jobs_user_created ON research_jobs(user_id, created_at);",
	"CREATE INDEX IF NOT EXISTS idx_research_jobs_status ON research_jobs(status);",
	`CREATE TABLE IF NOT EXISTS research_job_events (
		id TEXT PRIMARY KEY,
		job_id TEXT NOT NULL,
		user_id TEXT NOT NULL,
		type TEXT NOT NULL,
		phase TEXT NOT NULL,
		step TEXT,
		message TEXT NOT NULL,
		details TEXT,
		progress INTEGER CHECK (progress IS NULL OR (progress >= 0 AND progress <= 100)),
		section_id TEXT,
		section_title TEXT,
		section_index INTEGER,
		total_sections INTEGER,
		created_at TEXT NOT NULL
	);`,
	"CREATE INDEX IF NOT EXISTS idx_research_job_events_job_time ON research_job_events(job_id, created_at);",
	`CREATE TABLE IF NOT EXISTS document_research_links (
		link_id TEXT PRIMARY KEY,
		document_id TEXT NOT NULL,
		research_job_id TEXT NOT NULL,
		created_at TEXT NOT NULL,
		created_by TEXT NOT NULL
	);`,
	"CREATE INDEX IF NOT EXISTS idx_document_research_links_doc ON document_research_links(document_id);",
	"CREATE INDEX IF NOT EXISTS idx_document_research_links_job ON document_research_links(research_job_id);",
];
